### ISSUE TITLE
`Detect` incorrectly detects non-maven apps

### ISSUE THREAD

**Issue by danail-branekov** [paketo-buildpacks/maven#194]
Hello,

We have a [simple nodejs
app](https://github.com/cloudfoundry/korifi/tree/main/tests/smoke/assets/test-node-app)
that we build with paketo. Recently we discovered that the build suddenly started
to fail because of failures in the maven buildpack:

```
...
build Paketo Buildpack for Maven 6.10.0
build   https://github.com/paketo-buildpacks/maven
build   Build Configuration:
build     $BP_EXCLUDE_FILES                                                                 colon separated list of glob patterns, matched source files are removed
build     $BP_INCLUDE_FILES                                                                 colon separated list of glob patterns, matched source files are included
build     $BP_MAVEN_BUILD_ARGUMENTS  -Dmaven.test.skip=true --no-transfer-progress package  the arguments to pass to Maven
build     $BP_MAVEN_BUILT_ARTIFACT   target/*.[ejw]ar                                       the built application artifact explicitly.  Supersedes $BP_MAVEN_BUILT_MODULE
build     $BP_MAVEN_BUILT_MODULE                                                            the module to find application artifact in
build     $BP_MAVEN_DAEMON_ENABLED   false                                                  use maven daemon
build     $BP_MAVEN_POM_FILE         pom.xml                                                the location of the main pom.xml file, relative to the application root
build     $BP_MAVEN_SETTINGS_PATH                                                           the path to a Maven settings file
build     Creating cache directory /home/cnb/.m2
build   Compiled Application: Contributing to layer
build     Executing . --batch-mode -Dmaven.test.skip=true --no-transfer-progress package
build unable to invoke layer creator
build unable to contribute application layer
build error running build
build unable to start PTY
build exec: no command
build ERROR: failed to build: exit status 1

```

We thought it was weird to see the maven buildpack participating in the build
so we had a look at a test environment where older maven buildpack is deployed.
We configrmed that at this environment the maven buildpack is not
participating.

Therefore we created a
[test](https://github.com/paketo-buildpacks/maven/commit/76a4f463600a4f9a45aaaafaf419634ff8d75a72)
that runs `Detect` on the app. When ran with maven buildpack v6.8.0 the test
succeeds, i.e. `Detect` correctly determines that this is not a maven app.
However, with v6.9.0 onwards the test fails, i.e. `Detect` "believes" that this
is a maven app, hence the failure above.

## Expected Behavior
The test above succeeds

## Current Behavior
The test fails

## Possible Solution
`Detect` should return an empty result for the sample app (thus making the test
happy)

## Steps to Reproduce

1. Apply the commit above
2. Run `go test ./...`
3. See it fail

## Motivations
This seems like an incompatible change that breaks the build of apps that used
to build fine. In order to mitigate it we have pinned the previous version of
the java paketo buildpack but this is just a temporary solution.

cc @georgethebeatle

**Comment by loewenstein** [comment]
Could you try to reproduce with the latest release of the maven-buildpack? I think this should be fixed by now.

**Comment by fg-j** [comment]
We're still seeing the same behaviour in Paketo builder integration tests: https://github.com/paketo-buildpacks/base-builder/pull/595

**Comment by loewenstein** [comment]
Interesting @fg-j, I don't see this behavior with the latest release of the maven-buildpack in our Java meta-buildpack. But the Paketo java-buildpack packaged in the PR you mention does seem to include the latest version of maven-buildpack as well...

**Comment by dmikusa** [comment]
I think this is another bug related to recent logic changes to support more use cases with Maven. Apologizes. I have a PR that I believe will fix this. If you want to test, you can `pack build <app> --buildpack docker.io/dmikusa/paketo-java`. I pushed up the fix in that temporary image.

I've retested this with:

- a WAR/JAR (does not invoke Maven)
- Java source (invokes Maven)
- non-Java source (fails, as expected since it's not a Java app)
